[package]
name = "fps_dynamic"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glium = "*"
image = "*"
obj-rs = "0.7.1"
rand = "0.8.5"
dialoguer = "*"